### ISSUE TITLE
Rationale?

### ISSUE THREAD

**Issue by floer32** [Mermade/shins#1]
Why port? I'm curious, but also, others would be (potential users, potential contributors)

**Comment by MikeRalphson** [comment]
Ruby on Windows is a pain, and Slate on Windows is unsupported (presumably for that reason). I prefer to have everything in Node.js rather than using Ruby for one thing, PHP for another, Python for another etc, as I'm a little constrained on storage too.

I wanted to build an OpenAPI / Swagger to slate tool, (as swagger2slate appears to be broken and unmaintained) and integrate it with another Nodejs package, so it is useful for me to be able to very quickly regenerate Slate documentation (Widdershins should work exactly the same with native Slate as with Shins).

It's a good question, and I should probably add something more to the readme on the subject...

**Comment by floer32** [comment]
Cool! Thank you for explaining :)
