### ISSUE TITLE
Latest release is still marked as 2.1.1-0 instead of 2.6

### ISSUE THREAD

**Issue by rafadesu** [Mermade/shins#124]
Is there a reason why you are not updating the latest release to be the latest you release?

```
curl --silent https://api.github.com/repos/Mermade/shins/releases/latest | jq .tag_name
"v2.1.1-0"
```

**Comment by MikeRalphson** [comment]
The latest release with a GitHub release-notes etc is "v2.1.1-0", but the GitHub view "releases" shows https://github.com/Mermade/shins/releases/tag/v2.6.0 as the most recent "release" and "tag". I'm not sure how/why the API result may differ.

In any case, development of Shins has come to an end, it has been replaced by https://github.com/mermade/reslate

It is only due to a technicality that the repo is currently not archived.
