### ISSUE TITLE
Config passed to CLI via arguments have to be after input file name

### ISSUE THREAD

**Issue by simondean** [Mermade/shins#32]
There seems to be a bug where the arguments have to be passed after the input file name as otherwise the shins.js script tries to use the first config argument as the input file name. This works differently to widdershins where the arguments can be passed in before and after the input file name.

**Comment by MikeRalphson** [comment]
Yes, the two packages use different options parsers (partly because I was fed up with the number of breaking changes in `yargs` which cause *greenkeeper* to raise pull requests).

In `shins` the options are untyped so always swallow a value to their right. This can be avoided by using `--` between the options and the input filename.

**Comment by MikeRalphson** [comment]
Please continue the discussion over on [slant](https://github.com/mermade/slant) if still an issue.
