### ISSUE TITLE
Additional Javascript (e.g. clipboard support) buttons etc

### ISSUE THREAD

**Issue by truclyle** [Mermade/shins#79]
I'm hoping this question isn't too elementary but I was wondering how the workflow of shins works. For example, I want to incorporate ClipboardJS into the docs so that users can copy code to their clipboard. If I place the ClipboardJS's JavaScript file in `source/javascripts/lib` and my own JavaScript file in `source/javascripts/app`, how can I get my code to run before building the Markdown files into HTML files? 

My current process is to add two script tags in all_nosearch.inc, which means my copy buttons are attached after the HTML files are loaded. I want the copy buttons to be part of the HTML files. Hope this makes sense.

**Comment by MikeRalphson** [comment]
Hi, no such thing as a bad question.

Unfortunately, there's no way to get Javascript to run before the HTML is built, because of Shins static design.

Depending on how you generate your markdown, if it is hand-written, you can include your `<button...>` code before every code block instead of adding them via Javascript, or if you're using something like Widdershins, you should be able to amend the code templates to include the `<button...>` definitions.

**Comment by satvikmaker** [comment]
I think this is an amazing feature to have as as part of shins! What do you think @truclyle @MikeRalphson  ?

**Comment by MikeRalphson** [comment]
See https://github.com/slatedocs/slate/issues/903 and https://github.com/truclyle/shins/commit/41afb70530134d7896f42b197f8d63d6c88f7d2a

**Comment by MikeRalphson** [comment]
See also https://github.com/slatedocs/slate/issues/1220 will likely be coming in Slate 2.7.0

**Comment by MikeRalphson** [comment]
Included in Slate 2.7.0 and in [slant](https://github.com/mermade/slant) which is the successor to shins.
